src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java

According to upstream https://github.com/jenkinsci/cloudbees-folder-plugin/pull/20, https://github.com/jenkinsci/scm-api-plugin/pull/3, https://github.com/jenkinsci/branch-api-plugin/pull/8, https://github.com/jenkinsci/workflow-plugin/pull/220.
@reviewbybees esp. @stephenc

Adjustments

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/AbstractGitHubSCMSource.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
src/main/java/org/jenkinsci/plugins/github_branch_source/HttpsRepositoryUriResolver.java
src/main/java/org/jenkinsci/plugins/github_branch_source/OriginGitHubSCMSource.java
src/main/java/org/jenkinsci/plugins/github_branch_source/RepositoryUriResolver.java
src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator/config.jelly

[JENKINS-31445](https://issues.jenkins-ci.org/browse/JENKINS-31445)
@reviewbybees, especially @jglick and @amuniz

[JENKINS-31445] Include support for GitHub Enterprise

---

src/main/java/org/jenkinsci/plugins/github_branch_source/AbstractGitHubSCMSource.java
src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
src/main/java/org/jenkinsci/plugins/github_branch_source/RateLimitExceededException.java

[JENKINS-31574](https://issues.jenkins-ci.org/browse/JENKINS-31574)
@reviewbybees

[JENKINS-31574] Improved validation for Scan Credentials

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

As things stand right now, PR builds for public repositories are unsafe,
due to the fact that anyone can submit a PR that modifies Jenkinsfile.
As far as I am concerned, this is a regression; it used to be that this
plugin did not automatically pick up PR builds.
There are various efforts in progress to address this in different ways,
and there are also other project recognizers that are considered that
can change the situation.
But until that happens, please disable this feature, for it's too easy
for people to "incorrectly" use this functionality with public
repositories and make their Jenkins instances vulnerable.

Disable PR builds for public repos

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestGHEventSubscriber.java

@reviewbybees, specially @andresrc

Adapting to new parent POM

---

src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator/config.jelly

This guy should get the "add" button too

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubBuildStatusNotification.java
src/main/resources/org/jenkinsci/plugins/github_branch_source/Messages.properties

There's obviously tons more to internationalize, but we have to start
from somewhere

18n for things users see

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubBuildStatusNotification.java

It was broken here https://github.com/jenkinsci/github-branch-source-plugin/pull/19
@reviewbybees

Re-formatting the code

---

src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator/help-checkoutCredentialsId.html
src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator/help-scanCredentialsId.html
src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource/help-checkoutCredentialsId.html
src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource/help-scanCredentialsId.html

As a new user, it isn't clear what I'm supposed to specify here.
@reviewbybees

Doc improvement.

---

demo/plugins.txt

@reviewbybees, specially @jglick & @amuniz

Demo (dockerized) II

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestAction.java

Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/7 and intended to supersede #28.
@reviewbybees esp. @imeredith

[JENKINS-33309] Implement ChangeRequestAction

---

pom.xml
src/main/resources/index.jelly

@reviewbybees specially @rtyler and @daniel-beck

Display names has been changed

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

Noticed with @christ66 that this is pretty annoying.
@reviewbybees

Sort repositories in an organization

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java

[JENKINS-33815](https://issues.jenkins-ci.org/browse/JENKINS-33815)
@reviewbybees, specially @jglick

Validation for GH Organizations and GH User Accounts

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

Introduced here https://github.com/jenkinsci/github-branch-source-plugin/pull/38

Removed an unused import

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

@reviewbybees especially @jglick for that https://github.com/jenkinsci/github-branch-source-plugin/pull/40#discussion_r58936629

Wrong indentation

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/Endpoint.java
src/main/resources/org/jenkinsci/plugins/github_branch_source/Endpoint/help-apiUri.html

Reverts jenkinsci/github-branch-source-plugin#27

Revert "[JENKINS-33318] GHE server validation with private mode enabled"

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/Endpoint.java
src/main/resources/org/jenkinsci/plugins/github_branch_source/Endpoint/help-apiUri.html

Really, this PR is the same than https://github.com/jenkinsci/github-branch-source-plugin/pull/27
I merged that by mistake.
downstream of https://github.com/jenkinsci/github-api-plugin/pull/8
@reviewbybees

[JENKINS-33318] GHE server validation with private mode enabled

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

[JENKINS-34237](https://issues.jenkins-ci.org/browse/JENKINS-34237)
@reviewbybees

[JENKINS-34237] GH Org. and GH User Accounts are searched using insensitive case

---

src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java

@reviewbybees 
_Details, always details._

Coding style

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

[JENKINS-34120](https://issues.jenkins-ci.org/browse/JENKINS-34120)
```
Started
Connecting to github.com using recena/****** (recena (GH PAT))
Looking up seville-jam/workflow-helloworld
Getting remote branches...
Checking branch master
Jenkinsfile does not exist in this branch
Does not meet criteria
Checking branch recena-patch-1
Jenkinsfile does not exist in this branch
Does not meet criteria
0 branches were processed
Getting remote pull requests...
Checking pull request #PR-5
Submitted from origin repository, skipping
Checking pull request #PR-4
Jenkinsfile exists in this pull request
Not mergeable, but it will included
Met criteria
Checking pull request #PR-3
Jenkinsfile does not exist in this pull request
Does not meet criteria
Checking pull request #PR-2
Jenkinsfile exists in this …
```

[JENKINS-34120] Mergeability is not a condition to add a new job linked to a PR

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubWebhookListenerImpl.java

Added logging about webhooks received and how they are processed

---

src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

[JENKINS-34776](https://issues.jenkins-ci.org/browse/JENKINS-34776)
@reviewbybees

[JENKINS-34776] Jobs are removed if the remote is unavailable

---

src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java

[JENKINS-33623](https://issues.jenkins-ci.org/browse/JENKINS-33623)
@reviewbybees 
Thank @schulzh for reporting the issue.

[JENKINS-33623] Proxy configured in a wrong way

---

pom.xml

Bump parent POM to fix PCT against new cores.

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

Changelog must be produced for PR merge builds

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubBuildStatusNotification.java
src/main/resources/org/jenkinsci/plugins/github_branch_source/Messages.properties

Just to be consistent with the other statuses.

Moved queued message into Messages properties

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

Complements https://github.com/kohsuke/github-api/pull/295.
Also some logging I needed while evaluating [JENKINS-37359](https://issues.jenkins-ci.org/browse/JENKINS-37359). (I was trying to debug why I sometimes get socket timeouts on requests using anomalous `per_page=0`, but could not reproduce this later.)
@reviewbybees

Use the maximum page size to minimize HTTP requests

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/BranchSCMHead.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestSCMHead.java
src/main/resources/org/jenkinsci/plugins/github_branch_source/Messages.properties

[JENKINS-38987 Follow-up] Provide implementations of getPronoun() for the SCMHead/Source/Navigator

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubBranchFilter.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubPullRequestFilter.java
src/main/resources/org/jenkinsci/plugins/github_branch_source/Messages.properties

See [JENKINS-39026](https://issues.jenkins-ci.org/browse/JENKINS-39026) downstream of https://github.com/jenkinsci/branch-api-plugin/pull/53
@reviewbybees

[JENKINS-39026 Follow-up] Add ViewBranchFilter implementations for PRs and GitHub branches

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubOrgAction.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubRepoAction.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubRepositoryDescriptionColumn.java
src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubRepositoryDescriptionColumn/column.jelly
src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubRepositoryDescriptionColumn/columnHeader.jelly
src/main/resources/org/jenkinsci/plugins/github_branch_source/Messages.properties

See [JENKINS-39062](https://issues.jenkins-ci.org/browse/JENKINS-39062)
@reviewbybees

[JENKINS-39062] Move the GitHubRepositoryDescription column to github branch source

---

src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestSCMRevision.java

[JENKINS-39496](https://issues.jenkins-ci.org/browse/JENKINS-39496)
@reviewbybees

[JENKINS-39496] Make PullRequestSCMRevision public

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubBuildStatusNotification.java

Remove suppress warnings

---

src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator/config.jelly
src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource/config-detail.jelly

- Also make the API Endpoint visible when there is more that one API endpoint to select from
See [JENKINS-40451](https://issues.jenkins-ci.org/browse/JENKINS-40451)
@reviewbybees

[FIXED JENKINS-40451] Respect the API endpoint for credentials domains

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java

@reviewbybees
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/18

Navigators need to assign SCMSource IDs

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubBuildStatusNotification.java

See [JENKINS-40826](https://issues.jenkins-ci.org/browse/JENKINS-40826)
@reviewbybees

[FIXED-JENKINS-40826] Do not make network calls from the QueueListener thread

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubDefaultBranch.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

See [JENKINS-40833](https://issues.jenkins-ci.org/browse/JENKINS-40833)
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/20
@reviewbybees

[FIXED JENKINS-40833] Report primary branch

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubRepositoryEventSubscriber.java
src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestGHEventSubscriber.java

See [JENKINS-39114](https://issues.jenkins-ci.org/browse/JENKINS-39114)
@reviewbybees

[FIXED JENKINS-39114] Compare api, owner and repo case insensitively

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

See [JENKINS-39837](https://issues.jenkins-ci.org/browse/JENKINS-39837)
@reviewbybees

[FIXED JENKINS-39837] Set the GithubWeb browser when creating SCM

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

See [JENKINS-40875](https://issues.jenkins-ci.org/browse/JENKINS-40875)
@reviewbybees

[FIXED JENKINS-40875] Catch and diagnose permissions issues

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

See [JENKINS-41244](https://issues.jenkins-ci.org/browse/JENKINS-41244)
@reviewbybees

[FIXED JENKINS-41244] Be defensive when trying to set the browser

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/BranchSCMHead.java

Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/24
See [JENKINS-41121](https://issues.jenkins-ci.org/browse/JENKINS-41121)
@reviewbybees

[JENKINS-41121] Implement the SCMHeadMigration API

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

See [JENKINS-40652](https://issues.jenkins-ci.org/browse/JENKINS-40652)
@reviewbybees (as the minimal least risk fix)

[JENKINS-40652] Minimal fix for trusted revision

---

src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestGHEventSubscriber.java
src/main/java/org/jenkinsci/plugins/github_branch_source/PushGHEventSubscriber.java

See [JENKINS-41820](https://issues.jenkins-ci.org/browse/JENKINS-41820)
@reviewbybees

[FIXED JENKINS-41820] Missed some comparisons that were case sensitive

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubRepositoryEventSubscriber.java
src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestGHEventSubscriber.java
src/main/java/org/jenkinsci/plugins/github_branch_source/PushGHEventSubscriber.java

See [JENKINS-41815](https://issues.jenkins-ci.org/browse/JENKINS-41815)
@reviewbybees

[FIXED JENKINS-41815] Expose event origin to listeners

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java

Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/29
See [JENKINS-42000](https://issues.jenkins-ci.org/browse/JENKINS-42000)
@reviewbybees

[JENKINS-42000] Pick up SCM API update

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubBuildStatusNotification.java
src/main/resources/org/jenkinsci/plugins/github_branch_source/Messages.properties

See [JENKINS-42057](https://issues.jenkins-ci.org/browse/JENKINS-42057)
@reviewbybees

[FIXED JENKINS-42057] Report build errors as GitHub status Error

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

I suspect this is a typo. It doesn't fit the overall pattern.

Fix typo(?)

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubBuildStatusNotification.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubClosable.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubConsoleNote.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFile.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFileSystem.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMProbe.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

See [JENKINS-36121](https://issues.jenkins-ci.org/browse/JENKINS-36121)
@reviewbybees

[JENKINS-36121] Do not trip the rate limit

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestGHEventSubscriber.java
src/main/java/org/jenkinsci/plugins/github_branch_source/PushGHEventSubscriber.java

See [JENKINS-42254](https://issues.jenkins-ci.org/browse/JENKINS-42254)
@reviewbybees

[JENKINS-42254] Make the github sync delay configurable

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestGHEventSubscriber.java
src/main/java/org/jenkinsci/plugins/github_branch_source/PushGHEventSubscriber.java

[JENKINS-41736] Leverage the new event description API to expose event descriptions

---

pom.xml

See https://issues.jenkins-ci.org/browse/JENKINS-44581
@reviewbybees

[JENKINS-44581 Follow-up] Update dependency

---

src/main/java/org/jenkinsci/plugins/github_branch_source/Endpoint.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubConfiguration.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

See [JENKINS-45323](https://issues.jenkins-ci.org/browse/JENKINS-45323)
@reviewbybees (esp @vivek)

[FIXED JENKINS-45323] Add methods to manipulate the list of servers

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/Endpoint.java

Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/45
@reviewbybees

[JENKINS-45436] Pick up SCMName API

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
src/main/java/org/jenkinsci/plugins/github_branch_source/SSHCheckoutTrait.java
src/main/resources/org/jenkinsci/plugins/github_branch_source/Messages.properties
src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTraitsTest.java
src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTraitsTest.java
src/test/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTraitsTest/same_checkout_credentials.xml
src/test/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTraitsTest/same_checkout_credentials.xml

See [JENKINS-45467](https://issues.jenkins-ci.org/browse/JENKINS-45467)
@reviewbybees

[FIXED JENKINS-45467] Fixes for GitHub

---

src/main/java/org/jenkinsci/plugins/github_branch_source/BranchDiscoveryTrait.java

See [JENKINS-45551](https://issues.jenkins-ci.org/browse/JENKINS-45551)
@reviewbybees

[FIXED JENKINS-45551] The TODO comments were correct

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

See [JENKINS-45574](https://issues.jenkins-ci.org/browse/JENKINS-45574)
@reviewbybees (esp @daniel-beck)

[FIXED JENKINS-45574] When listing repositories of myself, only list the repositories that can actually be selected

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubBuildStatusNotification.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

POM update

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

See [JENKINS-46295](https://issues.jenkins-ci.org/browse/JENKINS-46295)
@reviewbybees

[FIXED JENKINS-46295] Handle the case where the query optimization is for a deleted branch

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFile.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFileSystem.java

See [JENKINS-46449](https://issues.jenkins-ci.org/browse/JENKINS-46449)
@reviewbybees

[FIXED JENKINS-46449] Better null safety

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

See [JENKINS-47775](https://issues.jenkins-ci.org/browse/JENKINS-47775)

[FIXED JENKINS-47775] Respect contract for a single PR fetyche when the PR is closed

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFileSystem.java

See [JENKINS-47585](https://issues.jenkins-ci.org/browse/JENKINS-47585)
@reviewbybees

[JENKINS-47585] Implement lightweight changelog

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

See [JENKINS-49945](https://issues.jenkins-ci.org/browse/JENKINS-49945)
- Fixes an issue with the regex for PR-n-HEAD and PR-n-MERGE
- Also defaults to assuming PR-n is a MERGE if you have not configured PR discovery (we discover branches and tags irrespective of whether branch or tag discovery is enabled, so looked like another bug)
- Also adds logging to help diagnose resolution behaviour

[FIXED JENKINS-49945] Fix regex and add some logging to help diagnose issues in resolve(thingName,listener)

---

src/main/java/org/jenkinsci/plugins/github_branch_source/PushGHEventSubscriber.java

Unfortunatelly this plugin was force installed by hard dependency 😡 from github-oauth-plugin 
https://github.com/jenkinsci/github-oauth-plugin/pull/78/files 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/github-branch-source-plugin/176)

Stop spamming jenkins log.

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTraitsTest.java

[JENKINS-45860](https://issues.jenkins-ci.org/browse/JENKINS-45860)

[JENKINS-45860] added a workaround for JENKINS-26535

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFileSystem.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
src/main/java/org/jenkinsci/plugins/github_branch_source/MergeWithGitSCMExtension.java
src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestAction.java
src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTraitsTest.java

Bring this plugin into the now to ease debugging and testing

Update all dependencies

---

.mvn/extensions.xml
.mvn/maven.config
pom.xml

@abayer @dwnusbaum @kshultzCB @rsandell 
Changing this plugin to use/produce incrementals.

Incrementalify this plugin

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubOrgWebHook.java

https://issues.jenkins-ci.org/browse/JENKINS-53694

Added PULL_REQUEST_REVIEW_COMMENT event trigger to webhook

---

pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java

Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/65.

[JENKINS-43802] Implementing retrieve/retrieveRevisions with an Item context

---

src/main/java/org/jenkinsci/plugins/github_branch_source/SSHCheckoutTrait.java

Since this Trait doesn't have a unique name it clashes with other plugins
https://issues.jenkins-ci.org/browse/JENKINS-53912

Adds custom name for SSHCheckoutTrait

---

src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTest.java
src/test/java/org/jenkinsci/plugins/github_branch_source/GithubSCMSourceTagsTest.java
src/test/resources/api/__files/body-yolo-tags-existent-multiple-tags.json
src/test/resources/api/mappings/mapping-yolo-tags-existent-multiple-tags.json

Added some tests to increase the code coverage for tags
I will be adding to this to increase tag, branch, and PR test coverage

Adding some lazy Iterator Tag tests

---

src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTest.java
src/test/java/org/jenkinsci/plugins/github_branch_source/GitSCMSourceBase.java
src/test/java/org/jenkinsci/plugins/github_branch_source/GithubSCMSourceBranchesTest.java
src/test/java/org/jenkinsci/plugins/github_branch_source/GithubSCMSourceTagsTest.java

Adding a base class for the Source tests so that the common code is organized

Base test class

---

src/main/java/org/jenkinsci/plugins/github_branch_source/BranchDiscoveryTrait.java
src/main/java/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait.java
src/main/java/org/jenkinsci/plugins/github_branch_source/OriginPullRequestDiscoveryTrait.java
src/main/java/org/jenkinsci/plugins/github_branch_source/SSHCheckoutTrait.java
src/main/java/org/jenkinsci/plugins/github_branch_source/TagDiscoveryTrait.java

Also see https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/256.

Make common traits consistent with bitbucket-branch-source-plugin

---

src/main/resources/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait/help-strategyId.html
src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator/help-credentialsId.html
src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource/help-credentialsId.html
src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource/help-repositoryUrl.html
src/main/resources/org/jenkinsci/plugins/github_branch_source/OriginPullRequestDiscoveryTrait/help-strategyId.html

- wording
- formatting
- consistency

Improve help texts

---

README.md

* NA
* Description:
* Fixed broken links to github in README.md
* Documentation changes:
* None

Corrected links to github in README.md

---

src/main/webapp/github-scm-source.js

- add missing semicolons
- consistent formatting
- explicit variable declaration

Improve Javascript code

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java

See https://github.com/jenkins-infra/jenkins.io/pull/2988#issuecomment-601878718.

Added doCheckAppID

---

src/test/java/org/jenkinsci/plugins/github_branch_source/AbstractGitHubWireMockTest.java
src/test/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitCheckerTest.java
src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFileSystemTest.java
src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTest.java
src/test/java/org/jenkinsci/plugins/github_branch_source/GitSCMSourceBase.java
src/test/java/org/jenkinsci/plugins/github_branch_source/PullRequestSCMRevisionTest.java
src/test/resources/api/mappings/mapping-orgs-stephenc.json

Disable proxying when not developing tests

Disable proxying when not developing tests

---

pom.xml
src/test/java/org/jenkinsci/plugins/github_branch_source/GithubSCMSourceTagsTest.java
src/test/resources/api/__files/body-orgs-cloudbeers-teams-justice-league-AHFpl.json
src/test/resources/api/mappings/mapping-body-orgs-cloudbeers-teams-justice-league-AHFpl.json

Upgrade github-api to 1.110

---

README.md

Update Changelog link: open GitHub releases tab

---

docs/github-app.adoc

Just updated a link in the readme
NA

update link to GitHub guide for creating an app

---

README.md

Updated link to Cloudbees documentation
NA

Updated link to Cloudbees documentation

---

pom.xml

Update bom version to latest (13)
n/a
N/A
No changes
@cloudbees/pipeline-team

Upgrade bom to 13

---

src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator/config.jelly
src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTraitsTest.java

When using an Organisation credentials are not used properly
See 
[JENKINS-59016](https://issues.jenkins-ci.org/browse/JENKINS-59016) for further information.

JENKINS-59016 fixing issues with certificates when using org

---

Jenkinsfile
pom.xml
src/main/webapp/github-scm-source.js

[JENKINS-64328](https://issues.jenkins-ci.org/browse/JENKINS-64328) for further information. 
See jira ticket ^^
But basically:
1. Create a multibranch pipeline
2. Configure with GitHub SCM
3. Try add another behaviour like build with tags, before this change it doesn't work and after it does
Help icon expanding is fixed in 2.270 with https://github.com/jenkinsci/jenkins/pull/5099
@bitwiseman @fqueiruga @dwnusbaum

JENKINS-64328 Fix behaviours with multibranch >2.263

---

pom.xml

See https://issues.jenkins.io/browse/JENKINS-64328
cc @dwnusbaum

Bump minimum version

---

src/main/java/org/jenkinsci/plugins/github_branch_source/BranchDiscoveryTrait.java

simple typo introduced in https://github.com/jenkinsci/github-branch-source-plugin/pull/376

fix: typo "ONLYP_RS" to "ONLY_PRS"

---

src/main/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitChecker.java
src/test/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitCheckerTest.java

Last change before switching over to use GitHubRateLimitChecker.

More adjusting of rate limit checking

---

src/main/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitChecker.java
src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceRequest.java
src/test/java/org/jenkinsci/plugins/github_branch_source/AbstractGitHubWireMockTest.java
src/test/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitCheckerTest.java
src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubOrgWebHookTest.java
src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMProbeTest.java

Move to using RateLimitChecker

---

pom.xml

Remove branch-api dependency

---

.gitattributes
src/main/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitChecker.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubBuildStatusNotification.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubNotificationContext.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubNotificationRequest.java
src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMBuilder.java
src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTraitsTest.java

Autoformatting in #392 found a bunch of typos, javadoc errors, and crufty edges which should be addressed regardless of formatting changes.

General typo fixes and cleanup

---

src/main/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitChecker.java
src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
src/test/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitCheckerTest.java

[JENKINS-65262](https://issues.jenkins.io/browse/JENKINS-65262) for further information. 
@bitwiseman

[JENKINS-65262] Remove possibility of long lock during connection lookup

---

pom.xml

Update pom.xml with gitHubRepo property

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java

[JENKINS-66148](https://issues.jenkins-ci.org/browse/JENKINS-66148) for further information. 
Add `plugin/` to path for "icon-github-repo icon-xlg".
@bitwiseman

Add path prefix plugin

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java

Increase page size to hopefully fix 
[JENKINS-67597](https://issues.jenkins-ci.org/browse/JENKINS-67597) for further information.

[JENKINS-67597] repo search topic: set page size

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestSCMRevision.java

Combines #624, #630, #631, #638, #642, #643, and #644 into one PR for easy testing and also crosses the Java 11 flag day.

Refresh plugin for December 2022

---

src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java

Analogous to https://github.com/jenkinsci/git-plugin/pull/1458.

Allow `$JENKINS_HOME/org.jenkinsci.plugins.github_branch_source.GitHubSCMProbe.cache/` to be overridden

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java
src/test/java/org/jenkinsci/plugins/github_branch_source/GithubAppCredentialsTest.java

for github app, print their ids for easier debugging

chore: when multiple installations found

---

src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
src/main/resources/org/jenkinsci/plugins/github_branch_source/TopicsTrait/help-topicList.html
src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTest.java
src/test/resources/api/mappings/mapping-search-repositories-based-on-topics-exclude-awesome-O8W78.json
src/test/resources/api/mappings/mapping-search-repositories-based-on-topics-octocat-exclude-awesome-O8W78.json

Allow excluding topics by prepending them with `-` sign.
See [JENKINS-65493](https://issues.jenkins.io/browse/JENKINS-65493) for further information.

[JENKINS-65493] Allow excluding by topics
