jenkinsci/github-branch-source-plugin

- pom.xml
Fixing parent pom resolution by adding `repositories` and `pluginRepositories` in pom.
```
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.jenkins-ci.plugins:github-branch-source:0.1-beta-2-SNAPSHOT (/Users/amuniz/workspace/github-branch-source-plugin/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.jenkins-ci.plugins:github-branch-source:0.1-beta-2-SNAPSHOT: Could not find artifact org.jenkins-ci.plugins:plugin:pom:1.609.2 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at no local POM @ line 4, column 13 -> [Help 2]
```
@reviewbybees
> Fix repositories and pluginRepositories

- pom.xml
We need to upgrade this dependency because this issue [JENKINS-30626](https://issues.jenkins-ci.org/browse/JENKINS-30626) [was included](https://github.com/jenkinsci/github-plugin/commit/03b1c879698eb76c8348b7e8b3514f1c9fb7ad41) in `github-plugin:1.14.0-alpha-2`. Next release was `github-plugin:1.14.0`
@reviewbybees especially, @jglick
> GitHub Plugin upgraded

- pom.xml
- src/main/java/org/jenkinsci/plugins/github_branch_source/AbstractGitHubSCMSource.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/HttpsRepositoryUriResolver.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/RepositoryUriResolver.java
[JENKINS-31482](https://issues.jenkins-ci.org/browse/JENKINS-31482)
This PR is a second part (review) of https://github.com/jenkinsci/github-branch-source-plugin/pull/6
@reviewbybees
> [JENKINS-31482] Be able to use HTTP/HTTPS for new GH API Endpoints

- pom.xml
- src/main/java/org/jenkinsci/plugins/github_branch_source/Endpoint.java
[JENKINS-31462](https://issues.jenkins-ci.org/browse/JENKINS-31462)
downstream https://github.com/jenkinsci/github-api-plugin/pull/5 (really https://github.com/kohsuke/github-api/pull/232)
@reviewbybees especially, @jglick
> [JENKINS-31462] GitHub Enterprise Servers validation

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/main/resources/org/jenkinsci/plugins/github_branch_source/Endpoint/help-apiUri.html
Better logs and error messages. Especially for SSL and invalid credentials.
> Better logs and error messages

- pom.xml
This upgrading is not technically needed but it is helpful because Pipeline Plugin requires as of `1.14`, `Jenkins 1.609.3`, and there is a relationship very common between both plugins.
@reviewbybees specially @jglick
> Upgraded Jenkins baseline

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
This is my solution to the problem I described in [JENKINS-33183](https://issues.jenkins-ci.org/browse/JENKINS-33183).  It just duplicates the authentication logic used when retrieving branches into the function that gets called to get the head of the current branch to build.  I am using this against a GitHub Enterprise server, so I don't think the API rate limiter applies to my use at all.  However, this may not be so great when used against the public GitHub servers.
This change maybe becomes less useful given that the last release disabled pull requests on public repositories, so I'm not sure if it's needed as much now since without it master still built but pull requests would error out.  I'm looking at that too, I understand limiting pull requests on public GitHub, but it seems that …
> [JENKINS-33183] Allow anon credentials when retrieving commit

- pom.xml
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestSCMHead.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/UntrustedPullRequestSCMRevision.java
[JENKINS-33256](https://issues.jenkins-ci.org/browse/JENKINS-33256)
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/5 and (implicitly) https://github.com/jenkinsci/workflow-plugin/pull/244.
@reviewbybees esp. @stephenc, @recena
> [JENKINS-33256] Untrusted PRs

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
As per https://issues.jenkins-ci.org/browse/JENKINS-34047
Saves confusion for those that have a lot of repos and orgs and mix Upper and lower case repo names, and may at first think things are unordered 
@reviewbybees
> [JENKINS-34047] Case insensitive sorting

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubBuildStatusNotification.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
[JENKINS-33306](https://issues.jenkins-ci.org/browse/JENKINS-33306)
```
Started by user anonymous
Connecting to GitHub using recena/****** (MyPAT)
> git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from 2 remote Git repositories
> git config remote.origin.url https://github.com/seville-jam/workflow-helloworld.git # timeout=10
Fetching upstream changes from https://github.com/seville-jam/workflow-helloworld.git
> git --version # timeout=10
using .gitcredentials to set credentials
> git config --local credential.helper store --file=/var/folders/y_/9z0ktk9d2lxcs18kw7l10h9w0000gn/T/git4664648971215722216.credentials # timeout=10
> git fetch --tags --progress https://github.com/seville-jam/workflow-helloworld.git +refs/heads/*:refs/remotes/origin/*
> git config --local …
```
> [JENKINS-33306] Stack trace printed when repo:status privilege missing

- .gitignore
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
- src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator/config.jelly
- src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator/help-excludes.html
- src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator/help-includes.html
[JENKINS-33305](https://issues.jenkins-ci.org/browse/JENKINS-33305)
@reviewbybees esp. @jglick
> [JENKINS-33305] Branch name filters at organization folder level

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
[JENKINS-34410](https://issues.jenkins-ci.org/browse/JENKINS-34410)
This is an alternative to https://github.com/jenkinsci/workflow-multibranch-plugin/pull/3
1. Better management of log message
1. Only one request to GitHub API
@reviewbybees
> Improved the search procedure of through SCMSourceCriteria

- pom.xml
Pipeline 1.15 [requires core 1.642.1](https://github.com/jenkinsci/pipeline-plugin/blob/workflow-1.15/pom.xml#L52), so only 1.14 can be set without bumping core here.
@reviewbybees
> Invalid combination of Core and Pipeline

- src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubWebhookListenerImpl.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestGHEventSubscriber.java
[JENKINS-34727](https://issues.jenkins-ci.org/browse/JENKINS-34727)
Just for review, do not merge until I get a answer from GitHub support to know what's the cache expiry time so I can set up the delay more accurately.
@reviewbybees
> [JENKINS-34727] Disable cache and delay branch indexing

- src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestGHEventSubscriber.java
Like #53, but applies to PR events, rather than origin repository events.
Tested in conjunction with #60.
@reviewbybees
> Added logging on when and why PR events are delivered

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubBuildStatusNotification.java
[JENKINS-36574](https://issues.jenkins-ci.org/browse/JENKINS-36574)
The idea is from #65. Tested successfully against https://github.com/cloudbeers/PR-demo/pulls when building all available options.
@reviewbybees
> [JENKINS-36574] Use the minimum number of status contexts necessary

- pom.xml
From https://github.com/jenkinsci/github-plugin/pull/84. Otherwise we get errors during `hpi:run` when browsing changelogs (cf. #70).
@reviewbybees
> Make sure we pick up GithubLinkAnnotator fix for WorkflowRun

- pom.xml
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubBuildStatusNotification.java
@jglick this updates the Build Status notifier to use the urls generated from the `DisplayURLProvider`. This is needed for Blue Ocean compatibility.
See https://github.com/jenkinsci/display-url-api-plugin
@jenkinsci/code-reviewers
> Update to use DisplayURLProvider

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
See [JENKINS-40876](https://issues.jenkins-ci.org/browse/JENKINS-40876)
When used downstream of https://github.com/jenkinsci/branch-api-plugin/pull/69 you can see the ObjectMetadataAction on PRs
@reviewbybees
> [FIXED JENKINS-40876] Retrieve the ObjectMetadataAction instances for heads

- pom.xml
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFileSystem.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestSCMHead.java
See [JENKINS-41453](https://issues.jenkins-ci.org/browse/JENKINS-41453)
- The pull requests are missing semi-required information and we need to migrate the key fields to prevent a build storm
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/25
@reviewbybees
> [JENKINS-41453] Fix fallout from fixing the overzealous migration of heads

- pom.xml
[JENKINS-42213](https://issues.jenkins-ci.org/browse/JENKINS-42213)
- Update baseline according to plugin dependencies.
- Check java.level is set to correct version.
- Bump and include plugins to fix PCT for 2.32.2
@reviewbybees @stephenc
> [JENKINS-42213] Changes in POM

- pom.xml
- src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
[JENKINS-41904](https://issues.jenkins-ci.org/browse/JENKINS-41904)
Corrects a regression apparently introduced in #94; `checkScanCredentials` actually _was_ checking for a null `context` to some extent, but not enough.
There is generally no `SCMSourceOwner` for an `SCMSource` being used from a library. Impossible for a global library. For a library scoped to a folder, there would be an `Item` always (may or may not be an `SCMSourceOwner`), and actually `Item` is all we care about.
@reviewbybees
> [JENKINS-41904] NPE in form validation when configuring an external library

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
See [JENKINS-41616](https://issues.jenkins-ci.org/browse/JENKINS-41616)
@reviewbybees
> [FIXED JENKINS-41616] Non-trusted pull requests should use a probe against the trusted revision not the PR's revision

- src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestGHEventSubscriber.java
This looks like a simple typo, as its different (and the logic seems correct) here: https://github.com/jenkinsci/github-branch-source-plugin/blob/f4403aecf858d25e5356a8eac100edd76911378b/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java#L642-L644
> Not building origin merge when webhook is received.

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTest.java
My team ran into this issue yesterday and spent a few hours trying to figure it out. We were seeing "Loading trusted files from base branch" messages for one of our organizations, and eventually traced it down to the organization being configured in one spot in Jenkins with a capital letter, versus all lower case elsewhere (including GitHub). Figured it was worth changing to prevent anyone else from getting similarly tripped up.
> Making source owner compare case-insensitive for trusted revision

- src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator/help-scanCredentialsId.html
- src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource/help-scanCredentialsId.html
The current UI hints about the need of creating "username with password" to access private repositories, but there is no explicit reference as to the fact that only these kind of credentials are supported (other credential kinds are silently filtered out).
At least https://issues.jenkins-ci.org/browse/JENKINS-38957 and https://issues.jenkins-ci.org/browse/JENKINS-34020 would have been prevented.
> UX: Document valid Scan Credentials

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestSCMHead.java
See [JENKINS-41246](https://issues.jenkins-ci.org/browse/JENKINS-41246)
@reviewbybees
> [FIXED JENKINS-41246] Guard against PRs from deleted forks

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubBuildStatusNotification.java
This should fix [JENKINS-46364](https://issues.jenkins-ci.org/browse/JENKINS-46364).
There appears to be an issue with the github-branch-source plugin where if you put a specification on a credential's domain, the credential will never be selected to authenticate when creating a GitHub Status. This appears to be because the apiUrl is not being passed when looking up the credential.
The project build log will display the following when this case occurs: `Could not update commit status. Message: {"message":"Must authenticate to access this API.","documentation_url":"https://developer.github.com/enterprise/2.9/v3"}`
I have tested it out for a hostname specification and was able to successfully have it fail before and succeed after the patch. I also reverted to 2.2.2 and the failure returned.
> [JENKINS-46364] Connector.lookupScanCredentials - pass apiUrl()

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
`github.getRepository` accepts github paths in `organization/repository` format.
See https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/GitHub.java#L425-L428
> [JENKINS-47171] `github.getRepository` expects 'org/repo' format

- pom.xml
[JENKINS-46967](https://issues.jenkins-ci.org/browse/JENKINS-46967)
- Upgrade to parent POM `2.33` to fix war-for-test issues.
- Current baseline for github-branch-source is `1.625.3` while baseline for branch-api `2.0.11` (dependency with scope test) is `1.642.3`.
@reviewbybees specially @stephenc
> [JENKINS-46967] Upgrading POM parent

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
My org folder scanning is failing, and I don't know why.
```
ERROR: [Thu Sep 14 13:26:12 UTC 2017] Could not fetch sources from navigator org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator@416977f4
hudson.AbortException: It seems https://api.github.com is unreachable
at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.checkApiUrlValidity(GitHubSCMSource.java:1022)
at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.retrieve(GitHubSCMSource.java:825)
at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:355)
at jenkins.scm.api.SCMSource.fetch(SCMSource.java:309)
at jenkins.branch.MultiBranchProjectFactory$BySCMSourceCriteria.recognizes(MultiBranchProjectFactory.java:263)
at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.recognizes(OrganizationFolder …
```
> Chain the cause exception and log in case of failure

- src/main/java/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/TagDiscoveryTrait.java
- src/main/resources/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait/TrustContributors/config.jelly
- src/main/resources/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait/TrustContributors/config.properties
- src/main/resources/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait/TrustEveryone/config.jelly
- src/main/resources/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait/TrustEveryone/config.properties
- src/main/resources/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait/TrustPermission/config.jelly
- src/main/resources/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait/TrustPermission/config.properties
- src/main/resources/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait/help-trust.html
- src/test/java/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait2Test.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTraitsTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTraitsTest.java
A more secure default, with better documentation of the effects of other choices.
@reviewbybees
> Recommend TrustPermission over TrustContributors

- src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestSCMRevision.java
See https://github.com/jenkinsci/scm-api-plugin/pull/52. Analogous to https://github.com/jenkinsci/git-plugin/pull/581.
> [JENKINS-50777] Exporting PullRequestSCMRevision.pullHash

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
Used in conjunction with https://github.com/jenkinsci/scm-api-plugin/pull/53 & https://github.com/jenkinsci/branch-api-plugin/pull/126.
> [JENKINS-50777] Export GitHubSCMSource.{repoOwner,repository}

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubNotificationContext.java
[JENKINS-47366](https://issues.jenkins-ci.org/browse/JENKINS-47366)
If a build result is set in the middle of a build and a secondary checkout is made, the default strategy reports that intermediate build result instead of "pending".
getDefaultState is currently called onCheckout and onCompleted. This change means any call to getDefaultState will just report pending while the build is in _BUILDING_ state (it will be in _POST_PRODUCTION_ for the onCompleted call)
> [JENKINS-47366] Avoid reporting premature build status

- src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestSCMHead.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestSCMRevision.java
https://issues.jenkins-ci.org/browse/JENKINS-50323
Make constructors public for extension plugins which work with the SCM Events API. This is possibly a naive suggestion, let me know if this is a bad idea and hopefully an alternative approach.
> JENKINS-50323 Public constructors for PullRequestSCMHead and PullRequestSCMRevision

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
See [JENKINS-54030](https://issues.jenkins-ci.org/browse/JENKINS-54030) and [JENKINS-54046](https://issues.jenkins-ci.org/browse/JENKINS-54046). This PR is a workaround for Windows masters, on which there is a file renaming bug in the caching. 
I've tested this to verify the following behaviors:
**Windows masters**
- Caching is disabled by default
- Caching can be turned back on temporarily by running `org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.cacheSize=20` (or some other number) in the script console. This change does not remain in place across a Jenkins restart.
- Caching can be changed permanently, by adding a system property in `C:\Path-To-Jenkins-Install\jenkins.xml` , inside the `<arguments>` tag, like this, where I set it to 33, so it would be easy to see it in the …
> [JENKINS-54046] Set default cache size to 0 for Windows masters

- src/main/java/org/jenkinsci/plugins/github_branch_source/BranchDiscoveryTrait.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/TagDiscoveryTrait.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTraitsTest.java
If both github and git branch plugins are installed on a Jenkins server, when attempting to specify the `branchDiscoveryTrait` or `tagDiscoveryTrait` the current versions of these plugins provide the same name. Adding the `@Symbol` annotation to specify a unique name will alleviate this naming collision.
> [JENKINS-45504] Added Symbol annotation to give discovery traits unique names

- src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestGHEventSubscriber.java
Here's a use case scenario that this submission addresses:  
We have a `when` conditional to skip CI builds when there is "WIP" in the pull request title. Our builds are slow running (~2-3 hours), so the ability to skip is absolutely necessary.   
A developer edits the pull request title, removes "WIP" and reruns the pipeline. 
Without this change to the plugin, the pipeline will use the old title, and not see the updated title. The `when` conditional will falsely evaluate to true because it is not reading the latest title of the pull request.
> Get updated pull request info when edited from Github [JENKINS-44715]

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
* the "cloudbees-bitbucket-branch-source" plugin also uses "General"
* both help files use "General"
* .../GitHubSCMNavigator/help-traits.html
* .../GitHubSCMSource/help-traits.html
> Name sections consistently

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMProbe.java
In the event that a directory contains both `JENKINSFILE` and `Jenkinsfile`. If we are looking for `Jenkinsfile` then without looping twice we would see `JENKINSFILE` first (because alpha sort puts uppercase before lowercase) and return the alert of mismatch... what we want to do is exhaustively search for the correct name and only in the event of no exact match should we check for alternative case variants
> Need to loop twice

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMProbe.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMProbeTest.java
If the fnf indicates problems with the ref instead of a normal 404.
This doesn't fix the issue but hopefully surface the error to the scan log for more diagnostic information.
> [JENKINS-54126] Rethrow file not found in probe stat

- src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMProbe.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMProbeTest.java
temporarily turn it off and try again
> [JENKINS-54126] if strange 404 when cache is on 

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMBuilder.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/SSHCheckoutTrait.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMBuilderTest.java
> [JENKINS-46094] Fix SSH Clone trait using agent credentials

- src/main/resources/org/jenkinsci/plugins/github_branch_source/Endpoint/config.jelly
See [JENKINS-54051](https://issues.jenkins-ci.org/browse/JENKINS-54051).
Moved location of checkMethod="post" from f:entry to f:textbox
- State before fix
- State after fix
> [JENKINS-54051] Fix error adding GitHub Enterprise Servers

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMBuilder.java
During release I got the following error.  
The troubleshooting page said to make this change https://wiki.jenkins.io/display/JENKINS/Hosting+Plugins#HostingPlugins-Workingaroundcommonissues.
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.159 s
[INFO] Finished at: 2019-03-27T12:55:27-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project github-branch-source: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - …
```
> Fixed missing imports for javadoc

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFileSystem.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestSCMRevision.java
> [JENKINS-43194] Use merge_commit_sha for master

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
When you load the list of repositories (`<select>`) it currently shows only _"Public and private repositories owned by current user"_, when you really want _"All public and private repositories that current user has access or collaborates to"_ ([FROM HERE](https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/GHMyself.java#L23)).
Right now it won't show the **private repos where you are collaborator**. It would still work if you manually change the select value using the browser's element inspector, so it is just a visual bug. The problem is that every time you change a setting you must do this again or itwill change the selected repo with the first one on the list.
Just changing the `RepositoryListFilter `value to `ALL` will correct this and show "_All public …
> Fixed the repository list not showing correctly all the repos

- Jenkinsfile
- pom.xml
Work in progress to make sure this plugin is constantly checked both building with JDK8 and JDK11.
This goes with the Jenkins Java 11 General Availability announcement made back in March, and we're making a pass to check plugins are looking good on a JDK11.
([to understand the Jenkinsfile content](https://wiki.jenkins.io/display/JENKINS/Java+11+Developer+Guidelines#Java11DeveloperGuidelines-MakesureyourpluginistestedinContinuousIntegrationonJava8andJava11atthesametime))
> [WIP] Java 11 readiness: build both on JDK8 and JDK11

- src/main/resources/org/jenkinsci/plugins/github_branch_source/BranchDiscoveryTrait/help-strategyId.html
This PR is in response to the branch-discovery help text:
"
Only branches that are also filed as PRs
This option exists to preserve legacy behaviour
when upgrading from older versions of the plugin.
NOTE: If you have an actual use case for this option
please file a pull request against this text.
"
We have a Jenkins pipeline that deploys dockers for
pull requests to a k8s cluster.  The Dockers are
built by a separate process, and tagged with the
branch name, so we want our k8s-deploy pipeline
to be fed the PR branch name in env.GIT_BRANCH,
so it can reference the appropriate docker.
Hope that makes sense.
> fix(discover branches): keep "PR branches" option

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFileSystem.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestSCMRevision.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTest.java
When scanning for new runs, PullRequestSCMRevision instances are compared.  While technically one combination of
base and pull commit produce the same merge, if we detect a new merge commit we should still treat that as a new revision.
For example:
Before this change, if a user closes a PR (unmerged) and then reopenes it, a repository scan would not treat the PR as changed.
After this change, a closing, reopening, and then scan will result in change being detected with a message like this (reformatted for clarity):
```
Changes detected: PR-3-merge (
58caa961c3fc5d68268e0d860670041b97cc86b0+edb61773c0185852a5d5c7afc17a924fee730363 (7c907cc0d0eaf15f2b84d030e23f5fd96e1b59d4) ->
58caa961c3fc5d68268e0d860670041b97cc86b0+edb61773c0185852a5d5c7afc17a924fee730363 …
```
> Fix identity comparison for GitHubSCMSource

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFileSystem.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestSCMRevision.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFileSystemTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/PullRequestSCMRevisionTest.java
We tried using strict merge commit handling to prevent cloning on master.
This resulted in some edge cases for some users where PRs would simply not build
and there was not viable workaround.
Change:
* Merge hash has been changed to best effort.  If it is missing or inconsistent,
Jenkins will gracefully revert to cloning on master.
* Most validity checking for merge hash has been moved to create time.
* Plugin tries harder than before to create a valid merge hash revision.
https://issues.jenkins-ci.org/browse/JENKINS-57371
> [JENKINS-57371] - Enable graceful fallback for merge hash

- src/main/java/org/jenkinsci/plugins/github_branch_source/PullRequestGHEventSubscriber.java
By default jenkins prints into system log all INFO messages, 
no sense to print every event in log by default .
The same as #176 but for other subscriber
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/github-branch-source-plugin/230)
> Stop spamming jenkins log

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMBuilderTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTraitsTest.java
- src/test/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTraitsTest/repositoryUrl.xml
See [JENKINS-58862](https://issues.jenkins-ci.org/browse/JENKINS-58862). New Multibranch projects configured to use repositories on GitHub Enterprise servers were always setting `apiUri` to point to `https://api.github.com`. These changes stop that from happening.
Also included are test changes so that the tests work correctly without directly calling `setApiUri()`.
CC @dwnusbaum , as I cannot directly request reviewers when opening PRs to this repo.
> [JENKINS-58862] MBPs configured via single URL always reference github.com

- pom.xml
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubBranchSourcesJCasCCompatibilityTest.java
- src/test/resources/org/jenkinsci/plugins/github_branch_source/configuration-as-code.yaml
See [JENKINS-57557](https://issues.jenkins-ci.org/browse/JENKINS-57557). _github-branch-sources_ is compatible with the last version of _configuration-as-code_. This PR adds an integration test to check possible future issues.
@varyvol @MRamonLeon @alecharp @rsandell 
@abayer @dwnusbaum @car-roll @bitwiseman as maintainers of the plugin
> [JENKINS-57557] Add test for JCasC compatibility

- pom.xml
The maven-hpi-plugin supports the used user property since v3.2 - see [changelog](https://github.com/jenkinsci/maven-hpi-plugin/blob/maven-hpi-plugin-3.2/README.md#32-2019-01-16).
> Simplify setting the Compatible-Since-Version property

- src/main/java/org/jenkinsci/plugins/github_branch_source/OriginPullRequestDiscoveryTrait.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTraitsTest.java
Now all traits consistently have a `@Symbol` annotation.
This improves configuration with JobDSL. Otherwise there is a clash e.g. with the bitbucket-branch-source-plugin [here](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/cloudbees-bitbucket-branch-source-2.6.0/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/OriginPullRequestDiscoveryTrait.java).
Also see https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/257.
> [JENKINS-45504] Add missing @Symbol to OriginPullRequestDiscoveryTrait

- src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource/config-detail.jelly
* [NGPIPELINE-775](https://cloudbees.atlassian.net/browse/NGPIPELINE-775)
* Description:
* When adding a github source, the `API endpoint` drop down list is partially visible when the `Repository Scan` radio button is selected.
The problem appears  to be in the GithubSCMSource jelly (`config-detail.jelly`). If there are no API Endpoints, an `invisibleEntry` is added to the `radioBlock`. However, it looks like there is a bug that `invisibleEntries` are still partially visible in a `radioBlock`.
(Technically, the list of API Endpoints is never empty as it always has a "Github" title as the first entry. I confirmed that the bug was still present when the list was truly empty.)
Since there is no reason to store an empty list of API Endpoints in an invisible entry, I …
> remove invisible entry from drop down list

- .gitignore
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMProbe.java
* [JENKINS-60353](https://issues.jenkins-ci.org/browse/JENKINS-60353)
* [JENKINS-54126](https://issues.jenkins-ci.org/browse/JENKINS-54126)
* Possibly others.
* Description:
* In short, this turns the workaround from [PR-204](https://github.com/jenkinsci/github-branch-source-plugin/pull/204) on all the time. 
* There will be a very small uptick in the number of API requests used with this change in place - but only in the event of getting a `40*` response code back from GitHub
* I don't expect this to solve all possible variants of the `Jenkinsfile not found` problem we've been battling for the last year and change. But some testing that @bitwiseman  and I worked on together, in the context of [JENKINS-60353](https://issues.jenkins-ci.org/browse/JENKINS-60353), shows …
> [JENKINS-60353] Enable PR-204 workaround all the time

- CHANGELOG.md
- README.md
- pom.xml
As the name implies, this migrates the changelog for GitHub Branch Source, from [this Wiki page](https://wiki.jenkins.io/display/JENKINS/GitHub+Branch+Source+Plugin), over to a Changelog here on the plugin repository. There's not much there other than the Changelog.
While I was here, I added links to relevant JENKINS Jira issues if there wasn't one there already.
I've also added a link in the README to [the CloudBees-hosted documentation](https://docs.cloudbees.com/docs/admin-resources/latest/plugins/github-branch-source).
For reviewers: the "automatic" wiki exporter tool left me with a fair amount of inconsistent formatting and other weirdness. Mostly left over from Jira links that didn't convert right. I did most of them by hand, so some extra eyes on those links might be good.
> Migrate wiki-based changelog to GitHub

- Jenkinsfile
- pom.xml
- src/test/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitCheckerTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFileSystemTest.java
* First part of fix to JENKINS-54126 and others.
* Description:
* It has been far too long since we've updated. This isn't quite done, but this is the last set of changes.  When the github-api-plugin is published I'll update the version in this PR. 
@car-roll @kshultzCB @joseblas @dwnusbaum
> Upgrade to github-api 1.105.1

- Jenkinsfile
- pom.xml
1.106 downgrades the commons-io dependency to 2.4 allowing the plugin to be used on Jenkins 2.150.3.
> Bump to github-api-plugin 1.106

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubConfiguration.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceContext.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceRequest.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/PushGHEventSubscriber.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/BranchDiscoveryTraitTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait2Test.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTraitTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubNotificationTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMBuilderTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTraitsTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTraitsTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/OriginPullRequestDiscoveryTraitTest.java
Removing this redundant type information cleans up code.
> Remove redundant type info

- src/main/resources/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait/help-trust.html
- src/main/resources/org/jenkinsci/plugins/github_branch_source/Messages.properties
* https://issues.jenkins-ci.org/browse/JENKINS-59485
* Description:
* Change only display name in drop down and in help text. Method/class name changes would probably require migration code, which I can provide in a second pull request if necessary.
* Documentation changes:
* No doc change, since trust level names are not mentioned in documentation
* Users/aliases to notify:
* I guess @bitwiseman ?
> [JENKINS-59485] Trust level "Contributors" is ambiguous, should be called "Collaborators" instead

- pom.xml
eaa297fba49998beca537ad00baf124895f7998a (in #273) was a bad merge, reverting critical parts of #269, including the ability to actually enter a secret key for an app.
I would urge anyone who ever resolves a Git merge conflict to use
```ini
[merge]
conflictstyle = diff3
```
(why is this not the default?!) or otherwise use a three-way merge tool, and of course check twice.
> Fix bad merge

- pom.xml
- src/main/java/org/jenkinsci/plugins/github_branch_source/JwtHelper.java
We've seen a few instances of the following log:
```
Caused: org.kohsuke.github.HttpException: Server returned HTTP response code: 401, message: 'Unauthorized' for URL: https://api.github.com/app/installations/111111/access_tokens
at org.kohsuke.github.Requester._fetchOrRetry(Requester.java:537)
at org.kohsuke.github.Requester._fetch(Requester.java:504)
Caused: org.kohsuke.github.HttpException: {"message":"'Expiration time' claim ('exp') is too far in the future","documentation_url":"https://developer.github.com/v3"}
at org.kohsuke.github.Requester.handleApiError(Requester.java:1049)
at org.kohsuke.github.Requester._fetch(Requester.java:506)
at org.kohsuke.github.Requester._fetch(Requester.java:496)
at org.kohsuke.github.Requester.fetch(Requester.java:412)
at …
```
> Tune expiration - account for clock sync

- pom.xml
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitSCMSourceBase.java
Update to plugin-pom 3.57.  Fixes to tests.
> Update to plugin-pom 3.57

- docs/github-app.adoc
- pom.xml
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java
- src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials/config.jelly
- src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials/help-owner.html
See https://github.com/jenkinsci/github-branch-source-plugin/pull/269#discussion_r395887018
To test it you need multiple organisation, ideally with private repos on both as public repos can be read even if haven't granted access, install the app to both organisations and follow the steps in the documentation
- [-] Link to JIRA ticket in description, if appropriate.
- [-] Automated tests have been added to exercise the changes
doc is in the repo
@jglick @bitwiseman @dwnusbaum
> Allow GitHub app to be installed in multiple orgs

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/JwtHelper.java
Amends #269 by caching the app installation token for almost the duration of its validity. Otherwise every time the token is requested, which would be for every API call to GitHub, Jenkins would by my count be making three additional HTTP requests: `/app`, `/app/installations`, and `/app/installations/:id/access_tokens`.
Tested directly via `jshell` (note that this requires https://github.com/jenkinsci/jenkins/pull/4603):
```java
var c = new org.jenkinsci.plugins.github_branch_source.GitHubAppCredentials(com.cloudbees.plugins.credentials.CredentialsScope.GLOBAL, "test", null, "…",
hudson.util.Secret.fromString(org.apache.commons.io.FileUtils.readFileToString(new java.io.File("/…-converted.pem"))))
var tok = c.getPassword().getPlainText()
new …
```
> Cache app installation token

- docs/implementation.adoc
- src/main/java/org/jenkinsci/plugins/github_branch_source/AbstractGitHubNotificationStrategy.java
Amends #162. An `ExtensionPoint` is an interface you could implement as a singleton and apply an `@Extension` to. (Traditionally it is also used on `Describable`s, though technically the actual extension point is the corresponding `Descriptor`.) https://github.com/jenkinsci/github-scm-trait-notification-context-plugin/blob/f5cb5c1a32fc6da2775d6791285d5a5901dbee8a/src/main/java/org/jenkinsci/plugins/githubScmTraitNotificationContext/NotificationContextTrait.java#L51-L76 confirms that the actual extension point here remains the `SCMSourceTrait[Descriptor]`.
> AbstractGitHubNotificationStrategy is not an ExtensionPoint

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java
Despite #291, using app authentication made checkouts on agents really slow. On a server I tested with using the `kubernetes` plugin, this reduces the time taken by `checkout scm` on a tiny github.com repo from 46s to 26s. Otherwise agent stack traces during checkout show lots of delays like
```
"pool-1-thread-11 for …
at java.lang.Object.wait(Native Method)
-  waiting on hudson.remoting.RemoteInvocationHandler$RPCRequest@7745dfbe
at hudson.remoting.Request.call(Request.java:177)
at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:288)
at com.sun.proxy.$Proxy5.fetch3(Unknown Source)
at hudson.remoting.RemoteClassLoader.findClass(RemoteClassLoader.java:211)
at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
-  locked …
```
> GitHubAppCredentials.writeReplace to avoid recalculating tokens

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
Repository discovery based on events is broken when using Github Apps.
```
Connecting to https://api.github.com using 61934/******
ERROR: https://api.github.com/user {"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/v3/users/#get-the-authenticated-user"}
java.io.FileNotFoundException: https://api.github.com/user
at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:243)
at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
at org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.bodyStream(GitHubHttpU …
```
> Skip self user scan when using Github Apps

- docs/github-app.adoc
Update GitHub App documentation to reflect that a GitHub App already has a built-in webhook that does not require creating a new webhook using the _Webhook_ permission. Furthermore, to take advantage of that built-in webhook, events must be enabled on the App's _Permissions_ page.
Otherwise, if you wanted to use a separate webhook created by Jenkins using the credentials of the GitHub App, you would need to enable the _Admin_ permission, or else you would get the following error and no webhook:
```
Failed to add GitHub webhook for GitHubRepositoryName[host=github.example.com,username=test,repository=test]
java.lang.NullPointerException: There are no credentials with admin access to manage hooks on GitHubRepositoryName[host=github.example.com,username=test,repository=test]
at …
```
> docs(github-app): webhook correction

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFile.java
github-api v1.112 changes the structure of the exceptions thrown from GHContent.
This change handle both the new and the old structures.
> Handle change exeception tree for GHContent

- src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
Fixes a regression in #223. Untested; we need to add functional tests of app authentication with WireMock and agents.
[JENKINS-62655](https://issues.jenkins-ci.org/browse/JENKINS-62655) for further information.
> [JENKINS-62655] IllegalStateException caused by misuse of Jenkins.instance from an agent JVM

- src/main/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitChecker.java
- src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubConfiguration/help-apiRateLimitChecker.html
- src/main/resources/org/jenkinsci/plugins/github_branch_source/Messages.properties
- src/test/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitCheckerTest.java
The current messaging for the Github API Usage rate limiter can lead users to think that Github itself is doing the limiting instead of Jenkins. This PR attempts to make it clearer that Jenkins is the one that is doing the rate limiting.
> Clarify api rate limit messaging

- pom.xml
- src/test/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitCheckerTest.java
Updates to the latest github-api-plugin.  Test changes are needed due to the new version discarding obviously inconsistent data. 
Downstream of https://github.com/jenkinsci/github-api-plugin/pull/60 .
> Use github-api v1.115

- pom.xml
- src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials/config.jelly
Alternative to https://github.com/jenkinsci/lib-multiline-secrets-ui/pull/1
Fixes Dark theme compatibility with GitHub app credentials
> Bump baseline to 2.176

- pom.xml
- src/main/java/org/jenkinsci/plugins/github_branch_source/JwtHelper.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/JwtHelperTest.java
If your github app private key contains these three letters - "RSA", Jenkins wrongly identifies it as PKCS#1 format key and throws the below error.
"Private key must be a PKCS#8 formatted string, to convert it from PKCS#1 use: openssl pkcs8 -topk8 -inform PEM -outform PEM -in current-key.pem -out new-key.pem -nocrypt"
I believe the code should either check for the complete string “BEGIN RSA PRIVATE KEY” or just the RSA word with spaces - " RSA ", (since private key content doesn't have any whitespaces)
@timja
> [JENKINS-63265] RSA substring in a PKCS#8 format private key is possible

- src/main/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitChecker.java
- src/main/resources/org/jenkinsci/plugins/github_branch_source/Messages.properties
- src/test/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitCheckerTest.java
This adds ApiRateLimitChecker.NoThrottle, which avoids checking the GitHub rate limits. This is useful for GitHub Enterprise installations. See [JENKINS-63078](https://issues.jenkins-ci.org/browse/JENKINS-63078) for further information. 
When this change is included, a new strategy will appear on the **Github API usage rate limiting strategy** selector, called **NoThrottle**, with the description _Ignore rate limit_. No requests to the rate_limit endpoint should be performed if it is selected.
> [JENKINS-63078] Allow ignoring rate limits

- src/main/java/org/jenkinsci/plugins/github_branch_source/JwtHelper.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/JwtHelperTest.java
I am running Windows with a local K8s cluster, which is running Jenkins. As part of the bootstrapping, I am loading up a .pem that was created in Windows. After much trial and error I realized this lib was not sanitizing the windows specific line endings. This change fixes that.
I tested this change on my own Jenkins instance by running the following script successfully:
```groovy
import jenkins.model.*
import hudson.util.Secret
import org.jenkinsci.plugins.github_branch_source.*
import com.cloudbees.plugins.credentials.*
def getContent(filePath) {
return new File(filePath).text
}
def token = new GitHubAppCredentials(CredentialsScope.GLOBAL, 'github-app', '', 1234, Secret.fromString(getContent('test.pem').replaceAll("\\n", "").replaceAll("\\r", "").replace("-----BEGIN PRIVATE KEY-----", …
```
> Account for Windows line endings in private key

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GithubAppCredentialsAppInstallationTokenTest.java
Follow on to #326. We shouldn't keep the app installation token as a bare `String`.  
I don't think this is a huge deal given how `Secret` is actually stored and serialized, but this is more correct regardless.
> Store token as Secret instead of String

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
https://github.com/jenkinsci/github-label-filter-plugin/pull/4 got as far as printing
```
Reason: org.kohsuke.github.GHFileNotFoundException: https://api.github.com/repos/…/…/issues/… {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/reference/issues#get-an-issue"}
```
CC @jvz
> Diagnostics for GHFileNotFoundException from retrieve

- src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
Before GitHub App Credentials, cache folders not being cleaned up was okay.  It was sometimes even an advantage since cached values that were extremely stable didn't have to be reloaded even across connection instances.  However, with  GitHub App Credentials the password (token) is regenerated on a regular basis, resulting in new connections with new caches.  
This change cleans up cache folders when GitHub App connections are no longer used. Behavior for non-GitHubAppCredential connections is unchanged to preserve the advantages of the existing behavior for standard credentials.
See [JENKINS-63711](https://issues.jenkins-ci.org/browse/JENKINS-63711) for further information.
> [JENKINS-63711] Cleanup GitHub App Credential cache folders 

- Jenkinsfile
https://github.com/jenkinsci/github-branch-source-plugin/pull/360#pullrequestreview-549550534
The current config does absolutely nothing as that's what the pom is pointing to
> Stop specifying the core version in Jenkinsfile

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GithubAppCredentialsTest.java
Made the settings that control GitHub Apps Credential caching into flags that can be controlled
in an effort to debug JENKINS-62249.
Users can now provide system properties or set values from the Jenkins console: 
```
org.jenkinsci.plugins.github_branch_source.GitHubAppCredentials.AFTER_TOKEN_GENERATION_DELAY_SECONDS
org.jenkinsci.plugins.github_branch_source.GitHubAppCredentials.STALE_BEFORE_EXPIRATION_SECONDS
org.jenkinsci.plugins.github_branch_source.GitHubAppCredentials.NOT_STALE_MINIMUM_SECONDS
```
`NOT_STALE_MINIMUM_SECONDS` is the minimum age at which a token can go stale.  Tokens will never go stale for at least this long after they are created.
`STALE_BEFORE_EXPIRATION_SECONDS` is how many seconds before expiration a token will go stale.  The larger the value the sooner the token …
> Adding GitHub Apps Creds debugging feature flags

- pom.xml
Extracts the dep added in #269 to its own plugin.
Subsumes #365.
> Extract dep on jjwt-api plugin

- src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubBuildStatusNotification.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFileSystem.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMProbe.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMProbeTest.java
The calls to connect and release for GitHub connections were not matched up.
We ended up having a few code paths with multiple release calls, resulting in errors.
This change fixes the mismatches and makes it less likely that future changes will break this.
it also makes the cache cleaning less aggressive, so that if this does occur again connections will be
less likely to get closed while still in use.
@timja Please try this as an incremental build to see if it addresses the issue. 
See 
[JENKINS-64595](https://issues.jenkins-ci.org/browse/JENKINS-64595) for further information.
> Fix connection caching - too many calls to release()

- src/main/java/org/jenkinsci/plugins/github_branch_source/BranchDiscoveryTrait.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/OriginPullRequestDiscoveryTrait.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTraitsTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTraitsTest.java
Minor refactor replace magic numbers with constants. They will appear in the Java docs making it easier to know which value is for what.
[JENKINS-64718](https://issues.jenkins-ci.org/browse/JENKINS-64718) for further information. 
- ~[ ] Automated tests have been added to exercise the changes~
- ~[ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.~
- ~[ ] Link to jenkins.io PR, or an explanation for why no doc changes are needed~
@timja @bitwiseman
> fix: use constants not magic numbers

- src/main/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitChecker.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitCheckerTest.java
github-api added a facility to automatically check rate limits before each API call.  It does this using the result from the previous call when possible. It also automatically reports a safe "unknown" rate limit without querying the endpoint when using GHE that is not configured with rate limits. 
This change is a pure refactor of the existing `ApiRateLimitChecker` strategies to use method signatures similar to `github-api`'s `RateLimitChecker` without actually using the `RateLimitChecker` functionality.  It should be reviewed with `ignore whitespace` enabled.
> Refactor ApiRateLimitChecker in preparation for using github-api RateLimitChecker

- src/main/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitChecker.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitCheckerTest.java
The ApiRateLimitChecker included functionality to handle when the rate limit is reset "before expected".
If a real world scenario exists for this behavior, it is an extreme edge case. Meanwhile, the functionality
add unneeded complexity to the checkers and is not supported by the github-api RateLimitChecker class.
This change remove this extraneous functionality and fixes the test match.
This change in need to move to using the built-in github-api `RateLimitChecker` functionality.
> Remove rechecking/refreshed rate limit functionality

- pom.xml
We only want to manage the version of branch-api used not take an actual dependency on it.
> Remove direct dependency on branch-api

- src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFileSystem.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitCheckerTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubOrgWebHookTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMProbeTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GithubAppCredentialsTest.java
See [JENKINS-64911](https://issues.jenkins-ci.org/browse/JENKINS-64911) for further information. 
Check validity was following its own special path, getting the password to create a hash, this resulted in a new call to `gitHub.checkApiUrlValidity()` each time the app password needed to be refreshed.  This resulted in users encountering the GitHub App issue we've seen with failure to authenticate much more often.
This change removes that special path and dependence on `getPassword()`. This still does address the underlying issue with App credentials, but so it goes.
@timja
> [JENKINS-64911] Streamline validity check

- src/test/java/org/jenkinsci/plugins/github_branch_source/GithubAppCredentialsTest.java
I realized after committing that I still didn't fully verify JENKINS-64911 in #395 . 
This improves tests to fully cover this issue, verifying that the rate_limit endpoint is never touched for all code paths to get or refresh a token.
I have run the tests with and without the fix and verified they detect the problem correctly.
> Verify rate_limit is not called during GitHub App token refresh

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTest.java
Branch discover strategies have a different behavior on repository examination. If you set **Exclude branches that are also filed as PRs** or **Only branches that are also filed as PRs** a TAG examination is triggered when you open a Pull Request but if you select **All Branches** does not. However, when you close a pull request a TAG examination is triggered in every strategy. 
So, this pull request tries to prevent this useless examination in order to optimize the plugin performance and to avoid unnecessary requests to GitHub API.  
[JENKINS-65071](https://issues.jenkins-ci.org/browse/JENKINS-65071) for further information. 
@bitwiseman
> [JENKINS-65071] PR events should not trigger tags examination

- src/main/java/org/jenkinsci/plugins/github_branch_source/ExcludeForkedRepositoriesTrait.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorContext.java
- src/main/resources/org/jenkinsci/plugins/github_branch_source/Messages.properties
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTest.java
I want to be able to point jenkins at my personal github account, but ignore all the repos i've forked to submit PRs. I only want to build original repositories.
Reviewer things to note:
* ~Spacing is inconsitent between files. Sometimes its 4 sometimes its 2. I'm going to make another PR (#418) that adds an .editorconfig with spacing set to 2.~ spotless has apparently handled this
* I couldn't figure out how to generate the test files, they seem very much stephenc and cloudbees
* Enforcer is complaining about plugin versions, but I didn't change any of that
- [/] Automated tests have been added to exercise the changes
> Exclude Forks (Source != null) so original repos can be discovered and PR repos could be ignored

- pom.xml
See https://github.com/diffplug/spotless/blob/a7f25eb51c6d4006591ea911157e62d0213e320b/lib/src/main/java/com/diffplug/spotless/java/GoogleJavaFormatStep.java#L99
Versions differ depending on your JVM version.
I was adding this to one of my plugins based off of the config here, locally I was getting no failures but on CI I had a failure...
I tracked it down to the above
cc @bitwiseman @jtnord
> Use specific version of google java format

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
use a SystemProperty
`org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.mergeableStatusRetries`
to configure the number of times we retry to obtain the mergeable status
of a PR.  If GHE is slow (and sometime gh.com) then changing this from
the default value of 4 may help.
[JENKINS-64494](https://issues.jenkins-ci.org/browse/JENKINS-64494) for further information.
> [JENKINS-64494] number of tries to get the mergeable status is now configurable

- pom.xml
- src/test/java/org/jenkinsci/plugins/github_branch_source/GithubAppCredentialsTest.java
See https://github.com/jenkinsci/jenkins/pull/4538
The old API is restricted now and shouldn't be used next time baseline is updated.
No rush though
> Update log recorder API (test only)

- .git-blame-ignore-revs
To work around #392. https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view
Compare
* Before: https://github.com/jenkinsci/github-branch-source-plugin/blame/7f7aa425a9eb650fe7b75574bd8898bbe7f2b37d/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java#L1794
* After: https://github.com/jenkinsci/github-branch-source-plugin/blame/7154585c000eeda448d05a552a1e7abd7d5d65a4/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java#L1794
> Adding `.git-blame-ignore-revs`

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorContext.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/TopicsTrait.java
[JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX) for further information. 
Otherwise job-dsl users have to write this 😢 
https://github.com/hmcts/cnp-jenkins-config/blob/53615434932d02a6ee4e7abb04df88831138f911/jobdsl/organisations-beta.groovy#L169-L172
I've tested this manually, just create a topic, save, check xml config, restart and make sure everything still loads properly
I also put a breakpoint in to make sure it's called
After this change the job-dsl config will become:
```groovy
traits << 'org.jenkinsci.plugins.github__branch__source.TopicsTrait' {
topicList(config.topic)
}
```
naming isn't the best but probably a bit late
- ~[ ] Automated tests have been added to exercise the changes~ - I don't …
> Don't persist topics twice

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
When defining a GitHub organization pointing at a Github Enterprise instance running in private mode, the avatar URL can't be accessed directly. This is causing a broken icon to be displayed as well as layout problems in list view in recent Jenkins versions.
This patch detects if the remote instance is in private mode and fallbacks to the standard github icon in that case.
The organization folder needs to be saved after upgrading to apply the new logic.
Before
After
> Don't pull avatar if remote GitHub Enterprise uses private mode.

- src/main/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitChecker.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitCheckerTest.java
See [JENKINS-66401](https://issues.jenkins-ci.org/browse/JENKINS-66401) for further information. 
- Test 1) ensure there are no GitHub servers/endpoints configured, then trigger an operation that uses the branch source without the api rate limit configured explicitly. An easy operation I've found is `readTrusted`, which will trigger this behavior the *first* time it is called for a commit. After that, it seems to cache the commit and doesn't need to actually call the GitHub API. I've been using a single PR and amending the commit to trigger it each time, that seems to work well. The message in the System logs (not the job logs) should state that the API URL used is the public github endpoint.
- Test 2) add a custom endpoint to the Jenkins configuration. Perform the same action as above to …
> JENKINS-66401 Use configured GitHub endpoint for default

- pom.xml
- src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
The HTTP client can currently not use proxies which require authentication.
By using a pre-configured base client this error should be mitigated
> Ensure that HTTP client can authenticate with proxy

- pom.xml
- src/test/resources/api/__files/body-(root)-XwEI7.json
- src/test/resources/api/__files/body-orgs-cloudbeers-teams-justice-league-AHFpl.json
- src/test/resources/api/mappings/mapping-body-orgs-cloudbeers-teams-repo-gOYDg.json
- src/test/resources/api/mappings/mapping-contents-fu-nMBRw.json
Teams api has been deprecated (see: https://github.blog/changelog/2022-02-22-sunset-notice-deprecated-teams-api-endpoints/). Org scans via team name no longer work. Fix was done in https://github.com/hub4j/github-api/issues/1386
Propagating the fix through to this plugin.
See also https://github.com/jenkinsci/github-api-plugin/pull/133
> bump github-api to support new teams api

- pom.xml
- src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubBuildStatusNotification.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFileSystem.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials/help-owner.html
- src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource/config-detail.jelly
- src/test/java/org/jenkinsci/plugins/github_branch_source/GithubAppCredentialsAppInstallationTokenTest.java
https://issues.jenkins.io/browse/JENKINS-62220
Uses https://github.com/jenkinsci/credentials-plugin/pull/293 to ensure that the `owner` field may be left blank yet the appropriate org will still be selected for a particular build. (At least assuming the lookup is via `CredentialsProvider.findCredentialById`, which passes a `Run`, as it would be for example in a `withCredentials` block.)
See discussions e.g. at https://github.com/jenkinsci/github-branch-source-plugin/pull/290#discussion_r401115617 or https://github.com/jenkinsci/github-branch-source-plugin/pull/269#discussion_r396535799.
Tested with https://github.com/jenkinsci/git-plugin/pull/1242 and an App installed on my account as well as a test org. Was able to create a multibranch project on a private repo in my account
```groovy …
```
> [JENKINS-62220] Automatically select `owner` for `GitHubAppCredentials` acc. to context

- src/main/java/org/jenkinsci/plugins/github_branch_source/ExcludePrivateRepositoriesTrait.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorContext.java
- src/main/resources/org/jenkinsci/plugins/github_branch_source/ExcludePrivateTrait/config.jelly
- src/main/resources/org/jenkinsci/plugins/github_branch_source/ExcludePrivateTrait/help.html
- src/main/resources/org/jenkinsci/plugins/github_branch_source/Messages.properties
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTest.java
This PR adds an `ExcludePrivateRepositoriesTrait`. Quick disclaimer, I'm not a Java developer and none of these changes have been tested locally. I mostly just mimicked what I saw for the `ExcludePublicRepositoriesTrait` and inverted it. My team could really use this feature. Please let me know if there's anything I need to change.
> Add `ExcludePrivateRepositoriesTrait`

- pom.xml
- src/test/java/org/jenkinsci/plugins/github_branch_source/EventsTest.java
EventsTest was flickering because on high load system wait was finishing before event comes.
> fix flickering and improve speed in EventsTest

- pom.xml
- src/test/java/org/jenkinsci/plugins/github_branch_source/GithubAppCredentialsTest.java
Signed-off-by: Olivier Lamy <olamy@apache.org>
> upgrade core LTS to 2.346.1 and associated bom, fix test due to this upgrade

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTest.java
When using [GitHub EMU](https://docs.github.com/en/enterprise-cloud@latest/admin/identity-and-access-management/using-enterprise-managed-users-for-iam/about-enterprise-managed-users) (Enterprise Managed User) accounts, the username contains an underscore, which prevents PR builds from forked repos.
We have a CloudBees client impacted by this issue, and I saw the previous PR was held up due to lack of regression testcases, so this PR takes the regex fix from https://github.com/jenkinsci/github-branch-source-plugin/pull/421 and adds a testcase to catch regressions for this fix, with the hopes this will allow the fix to be merged.
The format of GitHub EMU accounts is documented at:
https://docs.github.com/en/enterprise-cloud@latest/admin/identity-and-access-management/managing-iam-for-your-en …
> [JENKINS-67946] Support underscores in user names (GitHub Enterprise Managed User accounts)

- src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials/help-privateKey.html
Omitting the `-out` parameter since the form is prompting you to paste in text, not upload a file, so may as well just print to stdout.
Omitting `-inform` / `-outform` since they seem to be inferred.
Moving `-in` to the end to make it more convenient to paste this example and then just delete the example filename and replace with the real value.
> More concise suggestion for `GitHubAppCredentials.privateKey`

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/main/resources/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait/help-strategyId.html
- src/main/resources/org/jenkinsci/plugins/github_branch_source/OriginPullRequestDiscoveryTrait/help-strategyId.html
When multibranch was first written, using PR merge build strategy seemed like a neat way to ensure that trunk was never broken. But this strategy comes with downsides:
* It can be expensive: as the number of open PRs grow, the time spent testing them can grow _quadratically_ rather than linearly: every time one is merged, all the remaining ones are rebuilt.
* It violates the principle of least surprise: `gh pr checkout 123 && make` can produce different results than CI.
* This plugin as well as `github-checks` submit a commit status or check but then need to account for the fact that the built commit might be an ephemeral merge commit and the submission actually needs to use the first parent—though it might not, even in merge strategy, if the PR head is already up to date.
* You can then …
> Change default PR build strategy from merge to head

- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTraitsTest.java
- src/test/resources/org/jenkinsci/plugins/github_branch_source/configuration-as-code.yaml
Without this PR, `mvn clean verify -Dtest=InjectedTest,org.jenkinsci.plugins.github_branch_source.GitHubBranchSourcesJCasCCompatibilityTest,org.jenkinsci.plugins.github_branch_source.GitHubSCMSourceTraitsTest` passes without `gitlab-branch-source` on the test classpath but fails with it.
With this PR, it passes both with and without `gitlab-branch-source` on the classpath.
Therefore, this PR is needed to add `gitlab-branch-source` to `jenkinsci/bom`.
> Adapt tests to the presence of `gitlab-branch-source` on the test classpath

- src/test/java/org/jenkinsci/plugins/github_branch_source/GithubAppCredentialsTest.java
In CI have have seen flakes from `GithubAppCredentialsAppInstallationTokenTest.` 
inspecting the logs shows the flakes are occurring as the CI system is too slow and has just passed the 5 seconds configured for the cache timeout when it was not expecting it to.
Increase the timeout to 10 seconds to reduce the flakes (which will unfortunately increate the test time slightly of these tests)
> deflake GithubAppCredentialsAppInstallationTokenTest

- .mvn/extensions.xml
- pom.xml
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTraitsTest.java
Allow this test to pass when `cloudbees-bitbucket-branch-source` is on the test classpath
> PCT compatibility with `cloudbees-bitbucket-branch-source`

- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTest.java
A brief summary describing the changes in this pull request. 
In our analysis of the project, we observed that the test `GitHubSCMSourceTest.testShouldRetrieveNullEvent` contains 1 unnecessary stubbing. 
Unnecessary stubbings are stubbed method calls that were never realized during test execution. Mockito recommends to remove unnecessary stubbings (https://www.javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/exceptions/misusing/UnnecessaryStubbingException.html). 
We propose below a solution to remove the unnecessary stubbing.
> Removed 1 unnecessary stubbing in GitHubSCMSourceTest.java

- src/test/java/org/jenkinsci/plugins/github_branch_source/GithubSCMSourceBranchesTest.java
A brief summary describing the changes in this pull request. 
In our analysis of the project, we observed that the test `GithubSCMSourceBranchesTest.testThrownErrorSingleBranchException` contains 1 unnecessary stubbing. 
Unnecessary stubbings are stubbed method calls that were never realized during test execution. Mockito recommends to remove unnecessary stubbings (https://www.javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/exceptions/misusing/UnnecessaryStubbingException.html). 
We propose below a solution to remove the unnecessary stubbing.
> Removed 1 unnecessary stubbing in GithubSCMSourceBranchesTest.java

- src/main/java/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/ForkPullRequestDiscoveryTrait2Test.java
[JENKINS-26535](https://issues.jenkins-ci.org/browse/JENKINS-26535) describes an issue where wildcards in generics aren't handled well and result in the inability to configure classes that use wildcards in Job DSL, such as the SCMHeadAuthority class used for the forked PR trust policy. To work around this issue, create a new abstract class named GitHubForkTrustPolicy which extends the necessary SCMHeadAuthority superclass with its proper generics and use it in the constructor instead. Update all the trust policies to extend from this abstract class so they can be used.
Example use:
```groovy
branchSources {
branchSource {
source {
github {
// snipped standard repository fields
traits {
gitHubBranchDiscovery {
strategyId 1
}
gitHubPullRequestDiscovery {
strategyId 1
}
gitHubForkDiscovery { …
```
> [JENKINS-60874] Configuring ForkPullRequestDiscoveryTrait using Job DSL

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
- src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator/config.jelly
- src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator/help-enableAvatar.html
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTest.java
Proposing a field configuration to enable / disable the Avatar action fetch that can be causing issues because of the anonymous call. Even with recent addition of a cache, this can still be a problem.
See [JENKINS-72030](https://issues.jenkins.io/browse/JENKINS-72030) for further information. 
I thought it would be a better to disable it by default after seeing recent discussions in https://github.com/jenkinsci/github-branch-source-plugin/pull/653#issuecomment-1722715577.
@jglick @bitwiseman @rsandell
> [JENKINS-72030] Add checkbox to enable/disable Avatar retrieval

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java
The change proposed fixes a left over from https://github.com/jenkinsci/github-branch-source-plugin/pull/706
Before:
After:
> Fix GH icon for app credentials

- src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/Endpoint.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubConfiguration.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/main/java/org/jenkinsci/plugins/github_branch_source/SSHCheckoutTrait.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/EndpointTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTest.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/SSHCheckoutTraitTest.java
Allow users with Overall/Manage permission to configure endpoints. See [JENKINS-73053](https://issues.jenkins.io/browse/JENKINS-73053) for further information.
> [JENKINS-73053] Allow users with Overall/Manage permission to configure endpoints

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java
This encapsulate fields making possible to extend `GitHubAppCredentials` to retrieve properties from an alternative storage instead of field values.
Pseudo code:
```java
class AlternativeGitHubAppCredentials extends GitHubAppCredentials {
@Override
public getAppID() {
return retrieveFromExternalSystem("appId");
}
@Override
public getPrivateKey() {
return retrieveFromExternalSystem("privateKey");
}
}
```
See [JENKINS-73388](https://issues.jenkins-ci.org/browse/JENKINS-73388) for further information.
> [JENKINS-73388] Allow alternative implementation for GitHub App credentials

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java
GitHub App installed in multiple organizations get:
```
java.lang.IllegalArgumentException: Found multiple installations for GitHub app ID ... but none match credential owner "". Set the right owner in the credential advanced options to one of: ..., ...
at PluginClassLoader for github-branch-source//org.jenkinsci.plugins.github_branch_source.GitHubAppCredentials.generateAppInstallationToken(GitHubAppCredentials.java:244)
at PluginClassLoader for github-branch-source//org.jenkinsci.plugins.github_branch_source.GitHubAppCredentials.getToken(GitHubAppCredentials.java:295)
at PluginClassLoader for github-branch-source//org.jenkinsci.plugins.github_branch_source.GitHubAppCredentials.getPassword(GitHubAppCredentials.java:324)
at PluginClassLoader for …
```
> [JENKINS-73474] Fix GitHubAppCredentials owner inference

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
I got an Angry Jenkins while trying to validate a connection to a GitHub Enterprise server behind a VPN. System log said:
```
java.net.SocketTimeoutException: Connect timed out
at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
at java.base/java.net.Socket.connect(Socket.java:633)
at PluginClassLoader for okhttp-api//okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
at PluginClassLoader for okhttp-api//okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
at PluginClassLoader for okhttp-api//okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
at …
```
> Handle various errors from `doValidateRepositoryUrlAndCredentials`

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java
This would allow class that extends `GitHubAppCredentials` to benefit from the XStream serialization implemented in `GitHubAppCredentials`
@jeromepochat @jenkinsci/github-branch-source-plugin-developers
> Make GitHubAppCredentials#writeReplace protected for subclasses

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTest.java
In case a single repository processing fails during the Organizsation scan, the entire scan would be interrupted. Propose to handle the exception to no report the error and not break the loop.
See [JENKINS-75471](https://issues.jenkins.io/browse/JENKINS-75471) for further information.
> [JENKINS-75471] Gracefully skip repository if its processing fails in Organization scan

- pom.xml
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMProbeTest.java
In 2023 [WireMock](https://wiremock.org) updated their `groupId` and `artifactId` with the most recent major release of WireMock 3.
See [the announcement](https://www.wiremock.io/post/wiremock-3-goes-ga) for more details on the topic.
This PR migrates the `groupId` and `artifactId` to the new coordinates and also updates to the latest version.
This change enables receiving further updates on the dependency (e.g. via dependabot or renovate).
None. Rely on `ci.jenkins.io` to test it.
> Migrate from com.github.tomakehurst to org.wiremock

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
This is a follow up PR for [JENKINS-73474](https://issues.jenkins.io/browse/JENKINS-73474) where I'm fixing the issue while validating configuration when owner is set to empty.
On click of validate, it iterates through all the `GHAppInstallation` & check for valid repo `owner` match but since its empty hence no match founds & throws an error.
https://github.com/jenkinsci/github-branch-source-plugin/blob/fa7d4120f9c2f7b600fe3f3f8e477b7587a42e0b/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java#L230-L244
whereas when user configures the Github app credentials at time also `Test Connections` executes successfully without an error while owner is empty. It executes successfully because it reads the owner name from `GHAppInstallation`. …
> Fixed issue while validating the multibranch pipeline configuration 

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
The symbol ensures that command palette will show the symbol and not fall back to a default icon.
Before:
After:
> Use symbol for scm navigator

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTest.java
[JENKINS-73791](https://issues.jenkins.io/browse/JENKINS-73791): The retrieval of branches can fail the entire Branch Scanning if a `BranchDiscoveryTrait` strategy that involves checking on PRs is used while some PR parts cannot be retrieved with a 404 `FileNotFoundException`.
This is an extension of [JENKINS-56996](https://issues.jenkins.io/browse/JENKINS-56996) / https://github.com/jenkinsci/github-branch-source-plugin/pull/224.
@jenkinsci/github-branch-source-plugin-developers
> [JENKINS-73791] Prevent PR 404 on details to break Branches scan

- src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
- src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTest.java
This PR improves the handling of pull requests and commits authored by GitHub IA, Copilot, who may not have a real GitHub account or may lack a defined name or email.  
It prevents exceptions and ensures that these contributions are not discarded during indexing or processing.
---
- **Special handling for the "copilot" user:**
- If a pull request is authored by a user with login `"copilot"`, a synthetic `ContributorMetadataAction` is created with:
- Name: `"copilot"`
- Email: `"copilot@unknown.user"`
- This ensures PRs from Copilot are processed and visible, even though "copilot" is not a real GitHub user.
- **Other users:**
- For all other users, the contributor metadata is still created using the values returned by the GitHub API (`login`, `name`, and `email`) with no fallback.  
If …
> [JENKINS-75704] Fix Copilot user null name/email handling

- docs/github-app.adoc
https://github.com/jenkinsci/github-branch-source-plugin/pull/822 follow-up that fixes documentation bullet list.
See [JENKINS-75058](https://issues.jenkins.io/browse/JENKINS-75058)] for further information.
> Fix nested bullet list in documentation

- docs/github-app.adoc
This aims to clarify the limitations of the [GitHub App Credentials new options](https://github.com/jenkinsci/github-branch-source-plugin/pull/822) and add backward compatibility notes.
See [JENKINS-76056](https://issues.jenkins-ci.org/browse/JENKINS-76056) for further information. 
> [!NOTE]
> The release note for [1844.v4a_9883d49126](https://github.com/jenkinsci/github-branch-source-plugin/releases/tag/1844.v4a_9883d49126) will be updated with a link to the documentation after merge.
> [JENKINS-76056] Clarify inference limitations of GitHub App Credentials new options

- pom.xml
- src/test/resources/org/jenkinsci/plugins/github_branch_source/github-app-jcasc-minimal-expected-export.yaml
After the changes implemented on https://github.com/jenkinsci/configuration-as-code-plugin/pull/2712, there are some failing CasC test on the plugin:
com.cloudbees.jenkins.plugins.platform.CasCTest#smokeExport
The idea behind this PR is to upgrade the CasC plugin dependencies to 1995.v540b_50a_eb_0c1 and fix the failing tests.
> Fix Casc test upgrading after upgrading to CasC 1995.v540b_50a_eb_0c1
